-- From glfw3.h     
SGS_KEY_SPACE           =  32
SGS_KEY_APOSTROPHE      =  39  -- '
SGS_KEY_COMMA           =  44  -- , */
SGS_KEY_MINUS           =  45  -- - */
SGS_KEY_PERIOD          =  46  -- . */
SGS_KEY_SLASH           =  47  -- / */
SGS_KEY_0               =  48
SGS_KEY_1               =  49
SGS_KEY_2               =  50
SGS_KEY_3               =  51
SGS_KEY_4               =  52
SGS_KEY_5               =  53
SGS_KEY_6               =  54
SGS_KEY_7               =  55
SGS_KEY_8               =  56
SGS_KEY_9               =  57
SGS_KEY_SEMICOLON       =  59  -- ; */
SGS_KEY_EQUAL           =  61  -- = */
SGS_KEY_A               =  65
SGS_KEY_B               =  66
SGS_KEY_C               =  67
SGS_KEY_D               =  68
SGS_KEY_E               =  69
SGS_KEY_F               =  70
SGS_KEY_G               =  71
SGS_KEY_H               =  72
SGS_KEY_I               =  73
SGS_KEY_J               =  74
SGS_KEY_K               =  75
SGS_KEY_L               =  76
SGS_KEY_M               =  77
SGS_KEY_N               =  78
SGS_KEY_O               =  79
SGS_KEY_P               =  80
SGS_KEY_Q               =  81
SGS_KEY_R               =  82
SGS_KEY_S               =  83
SGS_KEY_T               =  84
SGS_KEY_U               =  85
SGS_KEY_V               =  86
SGS_KEY_W               =  87
SGS_KEY_X               =  88
SGS_KEY_Y               =  89
SGS_KEY_Z               =  90
SGS_KEY_LEFT_BRACKET    =  91  -- [ 
SGS_KEY_BACKSLASH       =  92  -- \ 
SGS_KEY_RIGHT_BRACKET   =  93  -- ]
SGS_KEY_GRAVE_ACCENT    =  96  -- `
SGS_KEY_WORLD_1         =  161 -- non-US #1
SGS_KEY_WORLD_2         =  162 -- non-US #2 ion keys 
SGS_KEY_E               =  256
SGS_KEY_ENTER           =  257
SGS_KEY_TAB             =  258
SGS_KEY_BACKSPACE       =  259
SGS_KEY_INSERT          =  260
SGS_KEY_DELETE          =  261
SGS_KEY_RIGHT           =  262
SGS_KEY_LEFT            =  263
SGS_KEY_DOWN            =  264
SGS_KEY_UP              =  265
SGS_KEY_PAGE_UP         =  266
SGS_KEY_PAGE_DOWN       =  267
SGS_KEY_HOME            =  268
SGS_KEY_END             =  269
SGS_KEY_CAPS_LOCK       =  280
SGS_KEY_SCROLL_LOCK     =  281
SGS_KEY_NUM_LOCK        =  282
SGS_KEY_PRINT_SCREEN    =  283
SGS_KEY_PAUSE           =  284
SGS_KEY_F1              =  290
SGS_KEY_F2              =  291
SGS_KEY_F3              =  292
SGS_KEY_F4              =  293
SGS_KEY_F5              =  294
SGS_KEY_F6              =  295
SGS_KEY_F7              =  296
SGS_KEY_F8              =  297
SGS_KEY_F9              =  298
SGS_KEY_F10             =  299
SGS_KEY_F11             =  300
SGS_KEY_F12             =  301
SGS_KEY_F13             =  302
SGS_KEY_F14             =  303
SGS_KEY_F15             =  304
SGS_KEY_F16             =  305
SGS_KEY_F17             =  306
SGS_KEY_F18             =  307
SGS_KEY_F19             =  308
SGS_KEY_F20             =  309
SGS_KEY_F21             =  310
SGS_KEY_F22             =  311
SGS_KEY_F23             =  312
SGS_KEY_F24             =  313
SGS_KEY_F25             =  314
SGS_KEY_KP_0            =  320
SGS_KEY_KP_1            =  321
SGS_KEY_KP_2            =  322
SGS_KEY_KP_3            =  323
SGS_KEY_KP_4            =  324
SGS_KEY_KP_5            =  325
SGS_KEY_KP_6            =  326
SGS_KEY_KP_7            =  327
SGS_KEY_KP_8            =  328
SGS_KEY_KP_9            =  329
SGS_KEY_KP_DECIMAL      =  330
SGS_KEY_KP_DIVIDE       =  331
SGS_KEY_KP_MULTIPLY     =  332
SGS_KEY_KP_SUBTRACT     =  333
SGS_KEY_KP_ADD          =  334
SGS_KEY_KP_ENTER        =  335
SGS_KEY_KP_EQUAL        =  336
SGS_KEY_LEFT_SHIFT      =  340
SGS_KEY_LEFT_CONTROL    =  341
SGS_KEY_LEFT_ALT        =  342
SGS_KEY_LEFT_SUPER      =  343
SGS_KEY_RIGHT_SHIFT     =  344
SGS_KEY_RIGHT_CONTROL   =  345
SGS_KEY_RIGHT_ALT       =  346
SGS_KEY_RIGHT_SUPER     =  347
SGS_KEY_MENU            =  348